-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 11:32:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`platenLabel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`platenLabel` (
  `idplatenLabel` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(255) NULL,
  PRIMARY KEY (`idplatenLabel`),
  UNIQUE INDEX `idplatenLabel_UNIQUE` (`idplatenLabel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Studio` (
  `idStudio` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(255) NULL,
  `stad` VARCHAR(255) NULL,
  `straatNaam` VARCHAR(255) NULL,
  `huisnummer` INT NULL,
  `postcode` CHAR(6) NULL,
  PRIMARY KEY (`idStudio`),
  UNIQUE INDEX `idStudio_UNIQUE` (`idStudio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artiest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artiest` (
  `idArtist` INT NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(255) NULL,
  `achternaam` VARCHAR(255) NULL,
  `artiestNaam` VARCHAR(255) NULL,
  `geboortedatum` DATE NULL,
  `platenLabel_idplatenLabel` INT NOT NULL,
  `Studio_idStudio` INT NOT NULL,
  PRIMARY KEY (`idArtist`, `platenLabel_idplatenLabel`, `Studio_idStudio`),
  UNIQUE INDEX `id_UNIQUE` (`idArtist` ASC),
  INDEX `fk_artiest_platenLabel_idx` (`platenLabel_idplatenLabel` ASC),
  INDEX `fk_artiest_Studio1_idx` (`Studio_idStudio` ASC),
  CONSTRAINT `fk_artiest_platenLabel`
    FOREIGN KEY (`platenLabel_idplatenLabel`)
    REFERENCES `mydb`.`platenLabel` (`idplatenLabel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artiest_Studio1`
    FOREIGN KEY (`Studio_idStudio`)
    REFERENCES `mydb`.`Studio` (`idStudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(255) NULL,
  `nummerAantal` INT NULL,
  `releaseDatum` DATE NULL,
  `albumcol` VARCHAR(45) NULL,
  `artiest_idArtist` INT NOT NULL,
  PRIMARY KEY (`idAlbum`, `artiest_idArtist`),
  UNIQUE INDEX `idalbum_UNIQUE` (`idAlbum` ASC),
  INDEX `fk_album_artiest1_idx` (`artiest_idArtist` ASC),
  CONSTRAINT `fk_album_artiest1`
    FOREIGN KEY (`artiest_idArtist`)
    REFERENCES `mydb`.`artiest` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenre`),
  UNIQUE INDEX `idGenre_UNIQUE` (`idGenre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre_has_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre_has_album` (
  `genre_idGenre` INT NOT NULL,
  `album_idAlbum` INT NOT NULL,
  `genre_has_album_id` INT NULL AUTO_INCREMENT,
  PRIMARY KEY (`genre_idGenre`, `album_idAlbum`),
  INDEX `fk_genre_has_album_album1_idx` (`album_idAlbum` ASC),
  INDEX `fk_genre_has_album_genre1_idx` (`genre_idGenre` ASC),
  UNIQUE INDEX `genre_has_album_id_UNIQUE` (`genre_has_album_id` ASC),
  CONSTRAINT `fk_genre_has_album_genre1`
    FOREIGN KEY (`genre_idGenre`)
    REFERENCES `mydb`.`genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_has_album_album1`
    FOREIGN KEY (`album_idAlbum`)
    REFERENCES `mydb`.`album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
