-- MySQL Script generated by MySQL Workbench
-- 03/14/17 13:09:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Boekenlijst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Boekenlijst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Boekenlijst` DEFAULT CHARACTER SET utf8 ;
USE `Boekenlijst` ;

-- -----------------------------------------------------
-- Table `Boekenlijst`.`auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Boekenlijst`.`auteur` (
  `auteur_id` INT NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(45) NOT NULL,
  `tussenvoegsel` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `geboortedatum` DATE NULL,
  PRIMARY KEY (`auteur_id`),
  UNIQUE INDEX `auteur_id_UNIQUE` (`auteur_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boekenlijst`.`uitgeverij`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Boekenlijst`.`uitgeverij` (
  `uitgeverij_id` INT NOT NULL AUTO_INCREMENT,
  `uitgeverij` VARCHAR(45) NOT NULL,
  `uitgeverijCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uitgeverij_id`),
  UNIQUE INDEX `uitgeverij_id_UNIQUE` (`uitgeverij_id` ASC),
  UNIQUE INDEX `uitgeverij_UNIQUE` (`uitgeverij` ASC),
  UNIQUE INDEX `uitgeverijCode_UNIQUE` (`uitgeverijCode` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boekenlijst`.`taal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Boekenlijst`.`taal` (
  `taal_id` INT NOT NULL AUTO_INCREMENT,
  `taal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`taal_id`),
  UNIQUE INDEX `taal_UNIQUE` (`taal` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boekenlijst`.`vertaling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Boekenlijst`.`vertaling` (
  `vertaling_id` INT NOT NULL AUTO_INCREMENT,
  `taal_id` VARCHAR(45) NOT NULL,
  `boekTitel` VARCHAR(45) NOT NULL,
  `paginas` INT NOT NULL,
  PRIMARY KEY (`vertaling_id`),
  UNIQUE INDEX `vertaling_id_UNIQUE` (`vertaling_id` ASC),
  INDEX `fk_vertaling_taal1_idx` (`taal_id` ASC),
  CONSTRAINT `fk_vertaling_taal1`
    FOREIGN KEY (`taal_id`)
    REFERENCES `Boekenlijst`.`taal` (`taal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boekenlijst`.`Boek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Boekenlijst`.`Boek` (
  `boek_id` INT NOT NULL AUTO_INCREMENT,
  `isbnNummer` INT NOT NULL,
  `auteur_id` VARCHAR(45) NOT NULL,
  `vertaling_id` INT NULL,
  `uitgeverij_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`boek_id`),
  UNIQUE INDEX `isbnNummer_UNIQUE` (`isbnNummer` ASC),
  UNIQUE INDEX `auteur_UNIQUE` (`auteur_id` ASC),
  INDEX `fk_Boek_uitgeverij1_idx` (`uitgeverij_id` ASC),
  UNIQUE INDEX `boek_id_UNIQUE` (`boek_id` ASC),
  INDEX `fk_Boek_vertaling1_idx` (`vertaling_id` ASC),
  CONSTRAINT `fk_Boek_auteur1`
    FOREIGN KEY (`auteur_id`)
    REFERENCES `Boekenlijst`.`auteur` (`auteur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Boek_uitgeverij1`
    FOREIGN KEY (`uitgeverij_id`)
    REFERENCES `Boekenlijst`.`uitgeverij` (`uitgeverij_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Boek_vertaling1`
    FOREIGN KEY (`vertaling_id`)
    REFERENCES `Boekenlijst`.`vertaling` (`vertaling_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
