-- MySQL Script generated by MySQL Workbench
-- 03/18/17 18:31:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema toernooi
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`toernooitype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`toernooitype` (
  `id_toernooitype` INT NOT NULL,
  `toernooitype` VARCHAR(45) NULL,
  PRIMARY KEY (`id_toernooitype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`land`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`land` (
  `id_land` INT NOT NULL,
  `land_naam` VARCHAR(45) NULL,
  PRIMARY KEY (`id_land`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uitslag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uitslag` (
  `id_uitslag` INT NOT NULL AUTO_INCREMENT,
  `goalteam_1` INT NOT NULL,
  `goalteam_2` INT NOT NULL,
  `winnaar` VARCHAR(45) NULL,
  PRIMARY KEY (`id_uitslag`),
  INDEX `fk_uitslag_land1_idx` (`winnaar` ASC),
  CONSTRAINT `fk_uitslag_land1`
    FOREIGN KEY (`winnaar`)
    REFERENCES `mydb`.`land` (`id_land`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rooster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooster` (
  `id_rooster` INT NOT NULL,
  `tijdstip` DATE NOT NULL,
  `id_team1` VARCHAR(45) NOT NULL,
  `id_team2` VARCHAR(45) NOT NULL,
  `id_uitslag` INT NOT NULL,
  PRIMARY KEY (`id_rooster`),
  INDEX `fk_rooster_uitslag1_idx` (`id_uitslag` ASC),
  INDEX `fk_rooster_land1_idx` (`id_team1` ASC),
  INDEX `fk_rooster_land2_idx` (`id_team2` ASC),
  CONSTRAINT `fk_rooster_uitslag1`
    FOREIGN KEY (`id_uitslag`)
    REFERENCES `mydb`.`uitslag` (`id_uitslag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rooster_land1`
    FOREIGN KEY (`id_team1`)
    REFERENCES `mydb`.`land` (`id_land`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rooster_land2`
    FOREIGN KEY (`id_team2`)
    REFERENCES `mydb`.`land` (`id_land`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`toernooi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`toernooi` (
  `id_toernooi` INT NOT NULL,
  `id_toernooitype` INT NOT NULL,
  `toernooi_jaar` DATE NOT NULL,
  `id_rooster` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_toernooi`),
  INDEX `fk_toernooi_toernooitype_idx` (`id_toernooitype` ASC),
  INDEX `fk_toernooi_rooster1_idx` (`id_rooster` ASC),
  CONSTRAINT `fk_toernooi_toernooitype`
    FOREIGN KEY (`id_toernooitype`)
    REFERENCES `mydb`.`toernooitype` (`id_toernooitype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_toernooi_rooster1`
    FOREIGN KEY (`id_rooster`)
    REFERENCES `mydb`.`rooster` (`id_rooster`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
